# # Docs: https://github.com/Azure/webapps-deploy

name: Build and deploy Node.js app to Azure Web App - ProjectShellAPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Install dependencies (without node_modules)
        run: |
          rm -rf node_modules
          npm install --omit=dev

      - name: Create deployment zip (exclude unnecessary files)
        run: |
          zip -r node-app.zip . -x "node_modules/*" ".git/*" ".github/*" "tests/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: node-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A1D8C78D2935497DA673DBDEFBB198E7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3A3B650969164F6E99E35453F500F52D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9AA23E0BC4D04C6F9DDBAFBFAA40FE74 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "ProjectShellAPI"
          slot-name: "Production"
          package: node-app.zip
