name: Build and deploy Node.js app to Azure Web App - ProjectShellAPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm ci

      - name: Zip project folder
        run: |
          zip -r node-app.zip * .[^.]* -x "node_modules/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: node-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Move zip to root
        run: mv node-app.zip ../node-app.zip
        working-directory: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5DCD04F926FE4101A9BB465675CAA89B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_39988DABF7AE4BBA8322C3370C05E70F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_37430AE814FB4BE9B8144E0DFC3DAA4F }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "ProjectShellAPI"
          slot-name: "production"
          package: ../node-app.zip
