# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - ProjectShellAPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm ci

      - name: Create deployment folder
        run: |
          mkdir deploy
          cp server.js package*.json deploy/
          # Optional: include more files if needed (like config, routes, views etc.)
          cp -r config controllers routes views deploy/

      - name: Zip deployment package
        run: |
          cd deploy
          zip -r ../node-app.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: node-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # Required for Azure login
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5DCD04F926FE4101A9BB465675CAA89B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_39988DABF7AE4BBA8322C3370C05E70F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_37430AE814FB4BE9B8144E0DFC3DAA4F }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "ProjectShellAPI"
          slot-name: "Production"
          package: node-app.zip
